replicaCount: 1

image:
  repository: "https://github.com/rgordon40/hello-world-app/hello-helm-app"
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  host: ""
  annotations: {}

nginx:
  service:
    type: ClusterIP
  replicaCount: 1
